/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/NotFound'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as appSeguridadAuditoriaRouteImport } from './routes/(app)/(Seguridad)/Auditoria'
import { Route as appGestionSolicitudesRouteImport } from './routes/(app)/(Gestion)/Solicitudes'
import { Route as appGestionProveedoresRouteImport } from './routes/(app)/(Gestion)/Proveedores'
import { Route as appGestionContactoRouteImport } from './routes/(app)/(Gestion)/Contacto'
import { Route as appGestionCalidadAguaRouteImport } from './routes/(app)/(Gestion)/CalidadAgua'
import { Route as appGestionActasRouteImport } from './routes/(app)/(Gestion)/Actas'
import { Route as appEdicionProyectosRouteImport } from './routes/(app)/(Edicion)/Proyectos'
import { Route as appEdicionImagenesRouteImport } from './routes/(app)/(Edicion)/Imagenes'
import { Route as appEdicionFAQRouteImport } from './routes/(app)/(Edicion)/FAQ'
import { Route as appAyudaManualesRouteImport } from './routes/(app)/(Ayuda)/Manuales'
import { Route as appAuthUnauthorizedRouteImport } from './routes/(app)/(Auth)/Unauthorized'
import { Route as appAuthResetPasswordRouteImport } from './routes/(app)/(Auth)/ResetPassword'
import { Route as appAuthLoginRouteImport } from './routes/(app)/(Auth)/Login'
import { Route as appAuthForgotPasswordRouteImport } from './routes/(app)/(Auth)/ForgotPassword'
import { Route as appGestionUsuariosIndexRouteImport } from './routes/(app)/(Gestion)/Usuarios/index'
import { Route as appGestionInventarioIndexRouteImport } from './routes/(app)/(Gestion)/Inventario/index'
import { Route as appGestionAfiliadosIndexRouteImport } from './routes/(app)/(Gestion)/Afiliados/index'
import { Route as appGestionUsuariosRolesRouteImport } from './routes/(app)/(Gestion)/Usuarios/Roles'
import { Route as appGestionInventarioUnidadesMedicionRouteImport } from './routes/(app)/(Gestion)/Inventario/UnidadesMedicion'
import { Route as appGestionInventarioMovimientosRouteImport } from './routes/(app)/(Gestion)/Inventario/Movimientos'
import { Route as appGestionInventarioCategoriasRouteImport } from './routes/(app)/(Gestion)/Inventario/Categorias'
import { Route as appGestionAfiliadosLecturasRouteImport } from './routes/(app)/(Gestion)/Afiliados/Lecturas'
import { Route as appGestionAfiliadosFacturasRouteImport } from './routes/(app)/(Gestion)/Afiliados/Facturas'
import { Route as appGestionInventarioMaterialesIndexRouteImport } from './routes/(app)/(Gestion)/Inventario/Materiales/index'
import { Route as appGestionInventarioMaterialesMedidoresRouteImport } from './routes/(app)/(Gestion)/Inventario/Materiales/Medidores'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/NotFound',
  path: '/NotFound',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/NotFound.lazy').then((d) => d.Route))
const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Home.lazy').then((d) => d.Route))
const appSeguridadAuditoriaRoute = appSeguridadAuditoriaRouteImport
  .update({
    id: '/(app)/(Seguridad)/Auditoria',
    path: '/Auditoria',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Seguridad)/Auditoria.lazy').then((d) => d.Route),
  )
const appGestionSolicitudesRoute = appGestionSolicitudesRouteImport
  .update({
    id: '/(app)/(Gestion)/Solicitudes',
    path: '/Solicitudes',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Solicitudes.lazy').then((d) => d.Route),
  )
const appGestionProveedoresRoute = appGestionProveedoresRouteImport
  .update({
    id: '/(app)/(Gestion)/Proveedores',
    path: '/Proveedores',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Proveedores.lazy').then((d) => d.Route),
  )
const appGestionContactoRoute = appGestionContactoRouteImport
  .update({
    id: '/(app)/(Gestion)/Contacto',
    path: '/Contacto',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Contacto.lazy').then((d) => d.Route),
  )
const appGestionCalidadAguaRoute = appGestionCalidadAguaRouteImport
  .update({
    id: '/(app)/(Gestion)/CalidadAgua',
    path: '/CalidadAgua',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/CalidadAgua.lazy').then((d) => d.Route),
  )
const appGestionActasRoute = appGestionActasRouteImport
  .update({
    id: '/(app)/(Gestion)/Actas',
    path: '/Actas',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Actas.lazy').then((d) => d.Route),
  )
const appEdicionProyectosRoute = appEdicionProyectosRouteImport
  .update({
    id: '/(app)/(Edicion)/Proyectos',
    path: '/Proyectos',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Edicion)/Proyectos.lazy').then((d) => d.Route),
  )
const appEdicionImagenesRoute = appEdicionImagenesRouteImport
  .update({
    id: '/(app)/(Edicion)/Imagenes',
    path: '/Imagenes',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Edicion)/Imagenes.lazy').then((d) => d.Route),
  )
const appEdicionFAQRoute = appEdicionFAQRouteImport
  .update({
    id: '/(app)/(Edicion)/FAQ',
    path: '/FAQ',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(app)/(Edicion)/FAQ.lazy').then((d) => d.Route))
const appAyudaManualesRoute = appAyudaManualesRouteImport
  .update({
    id: '/(app)/(Ayuda)/Manuales',
    path: '/Manuales',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Ayuda)/Manuales.lazy').then((d) => d.Route),
  )
const appAuthUnauthorizedRoute = appAuthUnauthorizedRouteImport
  .update({
    id: '/(app)/(Auth)/Unauthorized',
    path: '/Unauthorized',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Auth)/Unauthorized.lazy').then((d) => d.Route),
  )
const appAuthResetPasswordRoute = appAuthResetPasswordRouteImport
  .update({
    id: '/(app)/(Auth)/ResetPassword',
    path: '/ResetPassword',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Auth)/ResetPassword.lazy').then((d) => d.Route),
  )
const appAuthLoginRoute = appAuthLoginRouteImport
  .update({
    id: '/(app)/(Auth)/Login',
    path: '/Login',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(app)/(Auth)/Login.lazy').then((d) => d.Route))
const appAuthForgotPasswordRoute = appAuthForgotPasswordRouteImport
  .update({
    id: '/(app)/(Auth)/ForgotPassword',
    path: '/ForgotPassword',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Auth)/ForgotPassword.lazy').then((d) => d.Route),
  )
const appGestionUsuariosIndexRoute = appGestionUsuariosIndexRouteImport
  .update({
    id: '/(app)/(Gestion)/Usuarios/',
    path: '/Usuarios/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Usuarios/index.lazy').then((d) => d.Route),
  )
const appGestionInventarioIndexRoute = appGestionInventarioIndexRouteImport
  .update({
    id: '/(app)/(Gestion)/Inventario/',
    path: '/Inventario/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Inventario/index.lazy').then(
      (d) => d.Route,
    ),
  )
const appGestionAfiliadosIndexRoute = appGestionAfiliadosIndexRouteImport
  .update({
    id: '/(app)/(Gestion)/Afiliados/',
    path: '/Afiliados/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Afiliados/index.lazy').then(
      (d) => d.Route,
    ),
  )
const appGestionUsuariosRolesRoute = appGestionUsuariosRolesRouteImport
  .update({
    id: '/(app)/(Gestion)/Usuarios/Roles',
    path: '/Usuarios/Roles',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Usuarios/Roles.lazy').then((d) => d.Route),
  )
const appGestionInventarioUnidadesMedicionRoute =
  appGestionInventarioUnidadesMedicionRouteImport
    .update({
      id: '/(app)/(Gestion)/Inventario/UnidadesMedicion',
      path: '/Inventario/UnidadesMedicion',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(app)/(Gestion)/Inventario/UnidadesMedicion.lazy').then(
        (d) => d.Route,
      ),
    )
const appGestionInventarioMovimientosRoute =
  appGestionInventarioMovimientosRouteImport
    .update({
      id: '/(app)/(Gestion)/Inventario/Movimientos',
      path: '/Inventario/Movimientos',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(app)/(Gestion)/Inventario/Movimientos.lazy').then(
        (d) => d.Route,
      ),
    )
const appGestionInventarioCategoriasRoute =
  appGestionInventarioCategoriasRouteImport
    .update({
      id: '/(app)/(Gestion)/Inventario/Categorias',
      path: '/Inventario/Categorias',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(app)/(Gestion)/Inventario/Categorias.lazy').then(
        (d) => d.Route,
      ),
    )
const appGestionAfiliadosLecturasRoute = appGestionAfiliadosLecturasRouteImport
  .update({
    id: '/(app)/(Gestion)/Afiliados/Lecturas',
    path: '/Afiliados/Lecturas',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Afiliados/Lecturas.lazy').then(
      (d) => d.Route,
    ),
  )
const appGestionAfiliadosFacturasRoute = appGestionAfiliadosFacturasRouteImport
  .update({
    id: '/(app)/(Gestion)/Afiliados/Facturas',
    path: '/Afiliados/Facturas',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(app)/(Gestion)/Afiliados/Facturas.lazy').then(
      (d) => d.Route,
    ),
  )
const appGestionInventarioMaterialesIndexRoute =
  appGestionInventarioMaterialesIndexRouteImport
    .update({
      id: '/(app)/(Gestion)/Inventario/Materiales/',
      path: '/Inventario/Materiales/',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(app)/(Gestion)/Inventario/Materiales/index.lazy').then(
        (d) => d.Route,
      ),
    )
const appGestionInventarioMaterialesMedidoresRoute =
  appGestionInventarioMaterialesMedidoresRouteImport
    .update({
      id: '/(app)/(Gestion)/Inventario/Materiales/Medidores',
      path: '/Inventario/Materiales/Medidores',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(app)/(Gestion)/Inventario/Materiales/Medidores.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/Home': typeof HomeRoute
  '/NotFound': typeof NotFoundRoute
  '/ForgotPassword': typeof appAuthForgotPasswordRoute
  '/Login': typeof appAuthLoginRoute
  '/ResetPassword': typeof appAuthResetPasswordRoute
  '/Unauthorized': typeof appAuthUnauthorizedRoute
  '/Manuales': typeof appAyudaManualesRoute
  '/FAQ': typeof appEdicionFAQRoute
  '/Imagenes': typeof appEdicionImagenesRoute
  '/Proyectos': typeof appEdicionProyectosRoute
  '/Actas': typeof appGestionActasRoute
  '/CalidadAgua': typeof appGestionCalidadAguaRoute
  '/Contacto': typeof appGestionContactoRoute
  '/Proveedores': typeof appGestionProveedoresRoute
  '/Solicitudes': typeof appGestionSolicitudesRoute
  '/Auditoria': typeof appSeguridadAuditoriaRoute
  '/Afiliados/Facturas': typeof appGestionAfiliadosFacturasRoute
  '/Afiliados/Lecturas': typeof appGestionAfiliadosLecturasRoute
  '/Inventario/Categorias': typeof appGestionInventarioCategoriasRoute
  '/Inventario/Movimientos': typeof appGestionInventarioMovimientosRoute
  '/Inventario/UnidadesMedicion': typeof appGestionInventarioUnidadesMedicionRoute
  '/Usuarios/Roles': typeof appGestionUsuariosRolesRoute
  '/Afiliados/': typeof appGestionAfiliadosIndexRoute
  '/Inventario/': typeof appGestionInventarioIndexRoute
  '/Usuarios/': typeof appGestionUsuariosIndexRoute
  '/Inventario/Materiales/Medidores': typeof appGestionInventarioMaterialesMedidoresRoute
  '/Inventario/Materiales/': typeof appGestionInventarioMaterialesIndexRoute
}
export interface FileRoutesByTo {
  '/Home': typeof HomeRoute
  '/NotFound': typeof NotFoundRoute
  '/ForgotPassword': typeof appAuthForgotPasswordRoute
  '/Login': typeof appAuthLoginRoute
  '/ResetPassword': typeof appAuthResetPasswordRoute
  '/Unauthorized': typeof appAuthUnauthorizedRoute
  '/Manuales': typeof appAyudaManualesRoute
  '/FAQ': typeof appEdicionFAQRoute
  '/Imagenes': typeof appEdicionImagenesRoute
  '/Proyectos': typeof appEdicionProyectosRoute
  '/Actas': typeof appGestionActasRoute
  '/CalidadAgua': typeof appGestionCalidadAguaRoute
  '/Contacto': typeof appGestionContactoRoute
  '/Proveedores': typeof appGestionProveedoresRoute
  '/Solicitudes': typeof appGestionSolicitudesRoute
  '/Auditoria': typeof appSeguridadAuditoriaRoute
  '/Afiliados/Facturas': typeof appGestionAfiliadosFacturasRoute
  '/Afiliados/Lecturas': typeof appGestionAfiliadosLecturasRoute
  '/Inventario/Categorias': typeof appGestionInventarioCategoriasRoute
  '/Inventario/Movimientos': typeof appGestionInventarioMovimientosRoute
  '/Inventario/UnidadesMedicion': typeof appGestionInventarioUnidadesMedicionRoute
  '/Usuarios/Roles': typeof appGestionUsuariosRolesRoute
  '/Afiliados': typeof appGestionAfiliadosIndexRoute
  '/Inventario': typeof appGestionInventarioIndexRoute
  '/Usuarios': typeof appGestionUsuariosIndexRoute
  '/Inventario/Materiales/Medidores': typeof appGestionInventarioMaterialesMedidoresRoute
  '/Inventario/Materiales': typeof appGestionInventarioMaterialesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/Home': typeof HomeRoute
  '/NotFound': typeof NotFoundRoute
  '/(app)/(Auth)/ForgotPassword': typeof appAuthForgotPasswordRoute
  '/(app)/(Auth)/Login': typeof appAuthLoginRoute
  '/(app)/(Auth)/ResetPassword': typeof appAuthResetPasswordRoute
  '/(app)/(Auth)/Unauthorized': typeof appAuthUnauthorizedRoute
  '/(app)/(Ayuda)/Manuales': typeof appAyudaManualesRoute
  '/(app)/(Edicion)/FAQ': typeof appEdicionFAQRoute
  '/(app)/(Edicion)/Imagenes': typeof appEdicionImagenesRoute
  '/(app)/(Edicion)/Proyectos': typeof appEdicionProyectosRoute
  '/(app)/(Gestion)/Actas': typeof appGestionActasRoute
  '/(app)/(Gestion)/CalidadAgua': typeof appGestionCalidadAguaRoute
  '/(app)/(Gestion)/Contacto': typeof appGestionContactoRoute
  '/(app)/(Gestion)/Proveedores': typeof appGestionProveedoresRoute
  '/(app)/(Gestion)/Solicitudes': typeof appGestionSolicitudesRoute
  '/(app)/(Seguridad)/Auditoria': typeof appSeguridadAuditoriaRoute
  '/(app)/(Gestion)/Afiliados/Facturas': typeof appGestionAfiliadosFacturasRoute
  '/(app)/(Gestion)/Afiliados/Lecturas': typeof appGestionAfiliadosLecturasRoute
  '/(app)/(Gestion)/Inventario/Categorias': typeof appGestionInventarioCategoriasRoute
  '/(app)/(Gestion)/Inventario/Movimientos': typeof appGestionInventarioMovimientosRoute
  '/(app)/(Gestion)/Inventario/UnidadesMedicion': typeof appGestionInventarioUnidadesMedicionRoute
  '/(app)/(Gestion)/Usuarios/Roles': typeof appGestionUsuariosRolesRoute
  '/(app)/(Gestion)/Afiliados/': typeof appGestionAfiliadosIndexRoute
  '/(app)/(Gestion)/Inventario/': typeof appGestionInventarioIndexRoute
  '/(app)/(Gestion)/Usuarios/': typeof appGestionUsuariosIndexRoute
  '/(app)/(Gestion)/Inventario/Materiales/Medidores': typeof appGestionInventarioMaterialesMedidoresRoute
  '/(app)/(Gestion)/Inventario/Materiales/': typeof appGestionInventarioMaterialesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/Home'
    | '/NotFound'
    | '/ForgotPassword'
    | '/Login'
    | '/ResetPassword'
    | '/Unauthorized'
    | '/Manuales'
    | '/FAQ'
    | '/Imagenes'
    | '/Proyectos'
    | '/Actas'
    | '/CalidadAgua'
    | '/Contacto'
    | '/Proveedores'
    | '/Solicitudes'
    | '/Auditoria'
    | '/Afiliados/Facturas'
    | '/Afiliados/Lecturas'
    | '/Inventario/Categorias'
    | '/Inventario/Movimientos'
    | '/Inventario/UnidadesMedicion'
    | '/Usuarios/Roles'
    | '/Afiliados/'
    | '/Inventario/'
    | '/Usuarios/'
    | '/Inventario/Materiales/Medidores'
    | '/Inventario/Materiales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/Home'
    | '/NotFound'
    | '/ForgotPassword'
    | '/Login'
    | '/ResetPassword'
    | '/Unauthorized'
    | '/Manuales'
    | '/FAQ'
    | '/Imagenes'
    | '/Proyectos'
    | '/Actas'
    | '/CalidadAgua'
    | '/Contacto'
    | '/Proveedores'
    | '/Solicitudes'
    | '/Auditoria'
    | '/Afiliados/Facturas'
    | '/Afiliados/Lecturas'
    | '/Inventario/Categorias'
    | '/Inventario/Movimientos'
    | '/Inventario/UnidadesMedicion'
    | '/Usuarios/Roles'
    | '/Afiliados'
    | '/Inventario'
    | '/Usuarios'
    | '/Inventario/Materiales/Medidores'
    | '/Inventario/Materiales'
  id:
    | '__root__'
    | '/Home'
    | '/NotFound'
    | '/(app)/(Auth)/ForgotPassword'
    | '/(app)/(Auth)/Login'
    | '/(app)/(Auth)/ResetPassword'
    | '/(app)/(Auth)/Unauthorized'
    | '/(app)/(Ayuda)/Manuales'
    | '/(app)/(Edicion)/FAQ'
    | '/(app)/(Edicion)/Imagenes'
    | '/(app)/(Edicion)/Proyectos'
    | '/(app)/(Gestion)/Actas'
    | '/(app)/(Gestion)/CalidadAgua'
    | '/(app)/(Gestion)/Contacto'
    | '/(app)/(Gestion)/Proveedores'
    | '/(app)/(Gestion)/Solicitudes'
    | '/(app)/(Seguridad)/Auditoria'
    | '/(app)/(Gestion)/Afiliados/Facturas'
    | '/(app)/(Gestion)/Afiliados/Lecturas'
    | '/(app)/(Gestion)/Inventario/Categorias'
    | '/(app)/(Gestion)/Inventario/Movimientos'
    | '/(app)/(Gestion)/Inventario/UnidadesMedicion'
    | '/(app)/(Gestion)/Usuarios/Roles'
    | '/(app)/(Gestion)/Afiliados/'
    | '/(app)/(Gestion)/Inventario/'
    | '/(app)/(Gestion)/Usuarios/'
    | '/(app)/(Gestion)/Inventario/Materiales/Medidores'
    | '/(app)/(Gestion)/Inventario/Materiales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  NotFoundRoute: typeof NotFoundRoute
  appAuthForgotPasswordRoute: typeof appAuthForgotPasswordRoute
  appAuthLoginRoute: typeof appAuthLoginRoute
  appAuthResetPasswordRoute: typeof appAuthResetPasswordRoute
  appAuthUnauthorizedRoute: typeof appAuthUnauthorizedRoute
  appAyudaManualesRoute: typeof appAyudaManualesRoute
  appEdicionFAQRoute: typeof appEdicionFAQRoute
  appEdicionImagenesRoute: typeof appEdicionImagenesRoute
  appEdicionProyectosRoute: typeof appEdicionProyectosRoute
  appGestionActasRoute: typeof appGestionActasRoute
  appGestionCalidadAguaRoute: typeof appGestionCalidadAguaRoute
  appGestionContactoRoute: typeof appGestionContactoRoute
  appGestionProveedoresRoute: typeof appGestionProveedoresRoute
  appGestionSolicitudesRoute: typeof appGestionSolicitudesRoute
  appSeguridadAuditoriaRoute: typeof appSeguridadAuditoriaRoute
  appGestionAfiliadosFacturasRoute: typeof appGestionAfiliadosFacturasRoute
  appGestionAfiliadosLecturasRoute: typeof appGestionAfiliadosLecturasRoute
  appGestionInventarioCategoriasRoute: typeof appGestionInventarioCategoriasRoute
  appGestionInventarioMovimientosRoute: typeof appGestionInventarioMovimientosRoute
  appGestionInventarioUnidadesMedicionRoute: typeof appGestionInventarioUnidadesMedicionRoute
  appGestionUsuariosRolesRoute: typeof appGestionUsuariosRolesRoute
  appGestionAfiliadosIndexRoute: typeof appGestionAfiliadosIndexRoute
  appGestionInventarioIndexRoute: typeof appGestionInventarioIndexRoute
  appGestionUsuariosIndexRoute: typeof appGestionUsuariosIndexRoute
  appGestionInventarioMaterialesMedidoresRoute: typeof appGestionInventarioMaterialesMedidoresRoute
  appGestionInventarioMaterialesIndexRoute: typeof appGestionInventarioMaterialesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/NotFound': {
      id: '/NotFound'
      path: '/NotFound'
      fullPath: '/NotFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Seguridad)/Auditoria': {
      id: '/(app)/(Seguridad)/Auditoria'
      path: '/Auditoria'
      fullPath: '/Auditoria'
      preLoaderRoute: typeof appSeguridadAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Solicitudes': {
      id: '/(app)/(Gestion)/Solicitudes'
      path: '/Solicitudes'
      fullPath: '/Solicitudes'
      preLoaderRoute: typeof appGestionSolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Proveedores': {
      id: '/(app)/(Gestion)/Proveedores'
      path: '/Proveedores'
      fullPath: '/Proveedores'
      preLoaderRoute: typeof appGestionProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Contacto': {
      id: '/(app)/(Gestion)/Contacto'
      path: '/Contacto'
      fullPath: '/Contacto'
      preLoaderRoute: typeof appGestionContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/CalidadAgua': {
      id: '/(app)/(Gestion)/CalidadAgua'
      path: '/CalidadAgua'
      fullPath: '/CalidadAgua'
      preLoaderRoute: typeof appGestionCalidadAguaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Actas': {
      id: '/(app)/(Gestion)/Actas'
      path: '/Actas'
      fullPath: '/Actas'
      preLoaderRoute: typeof appGestionActasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Edicion)/Proyectos': {
      id: '/(app)/(Edicion)/Proyectos'
      path: '/Proyectos'
      fullPath: '/Proyectos'
      preLoaderRoute: typeof appEdicionProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Edicion)/Imagenes': {
      id: '/(app)/(Edicion)/Imagenes'
      path: '/Imagenes'
      fullPath: '/Imagenes'
      preLoaderRoute: typeof appEdicionImagenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Edicion)/FAQ': {
      id: '/(app)/(Edicion)/FAQ'
      path: '/FAQ'
      fullPath: '/FAQ'
      preLoaderRoute: typeof appEdicionFAQRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Ayuda)/Manuales': {
      id: '/(app)/(Ayuda)/Manuales'
      path: '/Manuales'
      fullPath: '/Manuales'
      preLoaderRoute: typeof appAyudaManualesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Auth)/Unauthorized': {
      id: '/(app)/(Auth)/Unauthorized'
      path: '/Unauthorized'
      fullPath: '/Unauthorized'
      preLoaderRoute: typeof appAuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Auth)/ResetPassword': {
      id: '/(app)/(Auth)/ResetPassword'
      path: '/ResetPassword'
      fullPath: '/ResetPassword'
      preLoaderRoute: typeof appAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Auth)/Login': {
      id: '/(app)/(Auth)/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof appAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Auth)/ForgotPassword': {
      id: '/(app)/(Auth)/ForgotPassword'
      path: '/ForgotPassword'
      fullPath: '/ForgotPassword'
      preLoaderRoute: typeof appAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Usuarios/': {
      id: '/(app)/(Gestion)/Usuarios/'
      path: '/Usuarios'
      fullPath: '/Usuarios/'
      preLoaderRoute: typeof appGestionUsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Inventario/': {
      id: '/(app)/(Gestion)/Inventario/'
      path: '/Inventario'
      fullPath: '/Inventario/'
      preLoaderRoute: typeof appGestionInventarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Afiliados/': {
      id: '/(app)/(Gestion)/Afiliados/'
      path: '/Afiliados'
      fullPath: '/Afiliados/'
      preLoaderRoute: typeof appGestionAfiliadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Usuarios/Roles': {
      id: '/(app)/(Gestion)/Usuarios/Roles'
      path: '/Usuarios/Roles'
      fullPath: '/Usuarios/Roles'
      preLoaderRoute: typeof appGestionUsuariosRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Inventario/UnidadesMedicion': {
      id: '/(app)/(Gestion)/Inventario/UnidadesMedicion'
      path: '/Inventario/UnidadesMedicion'
      fullPath: '/Inventario/UnidadesMedicion'
      preLoaderRoute: typeof appGestionInventarioUnidadesMedicionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Inventario/Movimientos': {
      id: '/(app)/(Gestion)/Inventario/Movimientos'
      path: '/Inventario/Movimientos'
      fullPath: '/Inventario/Movimientos'
      preLoaderRoute: typeof appGestionInventarioMovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Inventario/Categorias': {
      id: '/(app)/(Gestion)/Inventario/Categorias'
      path: '/Inventario/Categorias'
      fullPath: '/Inventario/Categorias'
      preLoaderRoute: typeof appGestionInventarioCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Afiliados/Lecturas': {
      id: '/(app)/(Gestion)/Afiliados/Lecturas'
      path: '/Afiliados/Lecturas'
      fullPath: '/Afiliados/Lecturas'
      preLoaderRoute: typeof appGestionAfiliadosLecturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Afiliados/Facturas': {
      id: '/(app)/(Gestion)/Afiliados/Facturas'
      path: '/Afiliados/Facturas'
      fullPath: '/Afiliados/Facturas'
      preLoaderRoute: typeof appGestionAfiliadosFacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Inventario/Materiales/': {
      id: '/(app)/(Gestion)/Inventario/Materiales/'
      path: '/Inventario/Materiales'
      fullPath: '/Inventario/Materiales/'
      preLoaderRoute: typeof appGestionInventarioMaterialesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(Gestion)/Inventario/Materiales/Medidores': {
      id: '/(app)/(Gestion)/Inventario/Materiales/Medidores'
      path: '/Inventario/Materiales/Medidores'
      fullPath: '/Inventario/Materiales/Medidores'
      preLoaderRoute: typeof appGestionInventarioMaterialesMedidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  NotFoundRoute: NotFoundRoute,
  appAuthForgotPasswordRoute: appAuthForgotPasswordRoute,
  appAuthLoginRoute: appAuthLoginRoute,
  appAuthResetPasswordRoute: appAuthResetPasswordRoute,
  appAuthUnauthorizedRoute: appAuthUnauthorizedRoute,
  appAyudaManualesRoute: appAyudaManualesRoute,
  appEdicionFAQRoute: appEdicionFAQRoute,
  appEdicionImagenesRoute: appEdicionImagenesRoute,
  appEdicionProyectosRoute: appEdicionProyectosRoute,
  appGestionActasRoute: appGestionActasRoute,
  appGestionCalidadAguaRoute: appGestionCalidadAguaRoute,
  appGestionContactoRoute: appGestionContactoRoute,
  appGestionProveedoresRoute: appGestionProveedoresRoute,
  appGestionSolicitudesRoute: appGestionSolicitudesRoute,
  appSeguridadAuditoriaRoute: appSeguridadAuditoriaRoute,
  appGestionAfiliadosFacturasRoute: appGestionAfiliadosFacturasRoute,
  appGestionAfiliadosLecturasRoute: appGestionAfiliadosLecturasRoute,
  appGestionInventarioCategoriasRoute: appGestionInventarioCategoriasRoute,
  appGestionInventarioMovimientosRoute: appGestionInventarioMovimientosRoute,
  appGestionInventarioUnidadesMedicionRoute:
    appGestionInventarioUnidadesMedicionRoute,
  appGestionUsuariosRolesRoute: appGestionUsuariosRolesRoute,
  appGestionAfiliadosIndexRoute: appGestionAfiliadosIndexRoute,
  appGestionInventarioIndexRoute: appGestionInventarioIndexRoute,
  appGestionUsuariosIndexRoute: appGestionUsuariosIndexRoute,
  appGestionInventarioMaterialesMedidoresRoute:
    appGestionInventarioMaterialesMedidoresRoute,
  appGestionInventarioMaterialesIndexRoute:
    appGestionInventarioMaterialesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
